### ISSUE TITLE
[IS-04-02] Errors after updating from websocket-client 1.2.1 to 1.4.1

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-testing#723]
While testing #721 to work around the breaking changes in `jsonref` 1.0.0, I tried:

```sh
pip3 uninstall -r requirements.txt
pip3 install -r requirements.txt
```

This updated my local `websocket-client` from 1.2.1 to 1.4.1 (released on 4 Sep 2022).

Running IS-04-02 now shows several tests failing with:
* Error opening websocket: 'socket' object has no attribute 'pending'

This is discussed here: https://github.com/websocket-client/websocket-client/issues/857
